apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-deploy
  labels: 
    app: nextjs-assignment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata: 
      labels:
        app: nextjs
    spec:
      containers:
      - name: nextjs
        image: ghcr.io/tanishq-309/wexa_ai_assignment:latest
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 2
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 1
        
